//! HTML Canvas visualizer for Fourier drawing.
//!
//! This module provides an HTML/JavaScript-based visualization that renders
//! the Fourier epicycles using the HTML5 Canvas API.

use std::fs;
use std::io::Error;

use crate::fft_drawer;
use crate::visualizer::Visualizer;

/// An HTML Canvas-based Fourier visualizer.
///
/// This visualizer generates a self-contained HTML file with embedded
/// JavaScript that animates the Fourier epicycles drawing the original path.
pub struct HTMLVisualizer {
    /// The output file path for the generated HTML.
    file_name: String,
}

impl HTMLVisualizer {
    /// Creates a new `HTMLVisualizer` that will write to the specified file.
    ///
    /// # Arguments
    ///
    /// * `file_name` - The path where the HTML file will be written
    ///
    /// # Example
    ///
    /// ```
    /// use fourier_svg::visualizer::html_visualizer::HTMLVisualizer;
    /// let visualizer = HTMLVisualizer::new("output.html".to_string());
    /// ```
    pub fn new(file_name: String) -> HTMLVisualizer {
        HTMLVisualizer { file_name }
    }

    /// Converts DrawData to JSON format for embedding in HTML.
    fn data_to_json(data: &[fft_drawer::DrawData]) -> String {
        if data.is_empty() {
            return String::new();
        }

        data.iter()
            .map(|d| {
                format!(
                    "{{\"s\": {:?}, \"r\": {:?}, \"a\": {:?}}}",
                    d.frequency, d.radius, d.angle
                )
            })
            .collect::<Vec<_>>()
            .join(",")
    }
}

impl Visualizer for HTMLVisualizer {
    /// Renders the Fourier data to an HTML file with canvas animation.
    ///
    /// The generated HTML file is self-contained and can be opened in any
    /// modern web browser. It includes:
    /// - An HTML5 canvas element
    /// - JavaScript code to animate the epicycles
    /// - The Fourier data embedded as JSON
    fn render(&self, data: Vec<fft_drawer::DrawData>) -> bool {
        let fourier_json_data = Self::data_to_json(&data);

        let content = format!(
            r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fourier Visualizer</title>
    <style>
        body {{
            margin: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            background-color: #f5f5f5;
        }}
        canvas {{
            border: 1px solid #ddd;
            background-color: white;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
    </style>
</head>
<body>
<canvas id="fourier_canvas" width="800" height="600"></canvas>
<script>
/**
 * Fourier Visualizer - Draws paths using rotating epicycles
 * Generated by fourier-svg
 */
let canvas = null;
let context = null;
let time = 0;

/**
 * Represents a 2D point
 */
class Point {{
    constructor(x, y) {{
        this.x = x;
        this.y = y;
    }}
    
    equals(point) {{
        return this.x === point.x && this.y === point.y;
    }}
    
    toString() {{
        return `(${{this.x}}, ${{this.y}})`;
    }}
}}

/**
 * Represents a single Fourier epicycle (rotating circle)
 */
class FourierCircle {{
    constructor(speed, radius, initialAngle) {{
        this.radius = radius / 2;
        this.speed = speed / 20;
        this.initialAngle = initialAngle;
    }}
    
    /**
     * Draws the epicycle arm from center point
     */
    draw(ctx, at) {{
        const angle = this.initialAngle + 2 * Math.PI * time * this.speed;
        const x = at.x + this.radius * Math.cos(angle);
        const y = at.y + this.radius * Math.sin(angle);
        
        ctx.beginPath();
        ctx.moveTo(at.x, at.y);
        ctx.lineTo(x, y);
        ctx.closePath();
        ctx.strokeStyle = 'rgba(202, 126, 86, 0.7)';
        ctx.lineWidth = 1;
        ctx.stroke();
    }}
    
    /**
     * Calculates the endpoint of this epicycle
     */
    nextCenter(at) {{
        const angle = this.initialAngle + 2 * Math.PI * time * this.speed;
        const x = at.x + this.radius * Math.cos(angle);
        const y = at.y + this.radius * Math.sin(angle);
        return new Point(x, y);
    }}
}}

let n;
let circles;
let animationId = 0;
const center = new Point(150, 150);
let wave = [];

/**
 * Initializes the Fourier visualization
 */
function initFourier(canvasElm, constants, count) {{
    canvas = canvasElm;
    context = canvas.getContext('2d');
    
    if (animationId !== 0) {{
        window.cancelAnimationFrame(animationId);
    }}
    
    n = count;
    circles = [];
    wave = [];
    
    for (let i = 0; i < count; i++) {{
        const constant = constants[i];
        circles[i] = new FourierCircle(constant.s, constant.r, constant.a);
    }}
    
    animationId = window.requestAnimationFrame(draw);
}}

/**
 * Draws the traced wave path with fading effect
 */
function drawWave(ctx) {{
    for (let i = 1; i < wave.length; i++) {{
        ctx.beginPath();
        ctx.moveTo(wave[i - 1].x, wave[i - 1].y);
        ctx.lineTo(wave[i].x, wave[i].y);
        ctx.closePath();
        
        // Fade out older parts of the wave
        const alpha = 1 - i / wave.length;
        ctx.strokeStyle = `rgba(0, 0, 0, ${{alpha}})`;
        ctx.lineWidth = 1;
        ctx.stroke();
    }}
}}

/**
 * Main animation loop
 */
function draw() {{
    context.clearRect(0, 0, canvas.width, canvas.height);
    
    // Calculate the endpoint through all epicycles
    let newCenter = circles[0].nextCenter(center);
    for (let i = 1; i < n; i++) {{
        circles[i].draw(context, newCenter);
        newCenter = circles[i].nextCenter(newCenter);
    }}
    
    // Add new point to wave and draw it
    wave.unshift(newCenter);
    drawWave(context);
    
    // Continue animation
    animationId = window.requestAnimationFrame(draw);
    
    // Update time
    time += 0.04;
    
    // Limit wave length for performance
    if (wave.length > 400) {{
        wave.pop();
    }}
}}

// Initialize on page load
window.onload = function() {{
    canvas = document.getElementById("fourier_canvas");
    const data = JSON.parse(`[{fourier_json}]`);
    initFourier(canvas, data, {count});
}};
</script>
</body>
</html>"#,
            fourier_json = fourier_json_data,
            count = data.len()
        );

        let save_result: Result<(), Error> = fs::write(&self.file_name, content);
        save_result.is_ok()
    }
}
